name: Demo App Android Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  version:
    name: Get version
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get flutter version
      id: get_flutter_version
      uses: its404/get-flutter-version@v1.0.0
    - name: Output flutter version
      run: echo 'version_number:' ${{ steps.get_flutter_version.outputs.version_number }} ' build_number:' ${{ steps.get_flutter_version.outputs.build_number }}

  build:
    name: Build APK and Create release
    needs: [ version ]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.10.1'
    - name: Get version.txt
      uses: actions/download-artifact@v2
      with:
        name: gitversion
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version.txt
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle

    - name: Get Pull Request Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.pr.outputs.pull_request_number }}
        commit: ${{ github.sha }}